- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/test/java/hudson/plugins/mercurial/MercurialSCMTest.java
This feature is useful when requiring the same repository to be used on downstream jobs (multijob).
Then the upstream job can pass the mercurial repo url to the downstream one. 
Now only the revision can be passed, which needs the repo url config to be duplicated in the downstream jobs..
This PR will simplify the repo config on the downstream jobs a lot (especially when having many ..)
> Expose new environment variable MERCURIAL_REPOSITORY_URL

- src/main/java/hudson/plugins/mercurial/browser/Kallithea.java
Add support for Kallithea (it is a fork of rhodeCode : https://kallithea-scm.org/). I don't know if add this directly in the mercurial plugin is the best way.
> Add support for kallithea

- src/main/java/hudson/plugins/mercurial/HgExe.java
- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/main/java/hudson/plugins/mercurial/MercurialTagAction.java
- src/main/resources/hudson/plugins/mercurial/Messages.properties
- src/test/java/hudson/plugins/mercurial/ChangeComparatorTest.java
- src/test/java/hudson/plugins/mercurial/HgExeFunctionalTest.java
- src/test/java/hudson/plugins/mercurial/MercurialSCMTest.java
- src/test/java/hudson/plugins/mercurial/MercurialTagActionTest.java
- src/test/java/hudson/plugins/mercurial/SCMTestBase.java
Hi!
I added support to get branch name of current or given revision. So build jobs can use MERCURIAL_REVISION_BRANCH to get the branch of tested revision.
https://issues.jenkins-ci.org/browse/JENKINS-10706
> [JENKINS-10706] Add env variable MERCURIAL_REVISION_BRANCH

- src/main/java/hudson/plugins/mercurial/MercurialTagAction.java
This change prevents breaking of dependend plugins. 
eg:
https://wiki.jenkins-ci.org/display/JENKINS/Feature+Branch+Notifier+Plugin
> Prevent breaking of dependen plugins

- src/main/java/hudson/plugins/mercurial/MercurialStatus.java
- src/test/java/hudson/plugins/mercurial/MercurialStatusTest.java
Using an environment variable in an Mercurial Repo parameter filled the error log with excessive stack traces, in spite of the parameter being valid for passing on to child jobs.
> [FIXED JENKINS-27316] Remove excessive stack traces in log

- pom.xml
- src/test/java/hudson/plugins/mercurial/MatrixProjectTest.java
- Migrate to 2.9 parent pom.
- Fix test - Utility method no longer existing.
@reviewbybees
> [JENKINS-34729] Migrate to 2.9 parent pom

- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
The current revset query used to grab changes grabs extra changes on large repositories with odd graphs. On our repository with 20000+ commits it is registering 10000+ changes everytime it builds.
I believe this is due to a bug in the revset query used to grab changes. Consider the following graph:
```
@  changeset:   5:2dccdf4acafc
|  branch:      b1
|  tag:         tip
|  parent:      3:c1c5663af0b7
|  summary:     wolo2
|
| o  changeset:   4:939721587c26
| |  branch:      b2
| |  parent:      1:1fd80701afc5
| |  summary:     wolo
| |
o |  changeset:   3:c1c5663af0b7
| |  branch:      b1
| |  summary:     frobnosticate
| |
o |  changeset:   2:a78553b9c3ae
|/    summary:     foobarbaz
|
o  changeset:   1:1fd80701afc5
|  summary:     foobar
|
o  changeset:   0:600d548d0dcb
summary: …
```
> [FIXED JENKINS-30120] Fix extra changes being found

- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
Mercurial changed the format for `--rev`, the branch name must be wrapped in quotes when `:0` is appended.
> [FIXED JENKINS-30120] Branches with space in name failing during changelog

- pom.xml
- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/test/java/hudson/plugins/mercurial/CachingSCMTest.java
- src/test/java/hudson/plugins/mercurial/MercurialSampleRepoRule.java
- src/test/java/hudson/plugins/mercurial/PipelineTest.java
- src/test/java/hudson/plugins/mercurial/SharingSCMTest.java
- src/test/java/hudson/plugins/mercurial/SwitchingSCMTest.java
[JENKINS-28121](https://issues.jenkins-ci.org/browse/JENKINS-28121)
Picks up tests from https://github.com/jenkinsci/workflow-scm-step-plugin/pull/4 and https://github.com/jenkinsci/workflow-multibranch-plugin/pull/17, and makes them pass when `CACHE_LOCAL_REPOS` is deleted.
@reviewbybees
> [FIXED JENKINS-28121] Need to mkdirs before clone

- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/test/java/hudson/plugins/mercurial/SCMTestBase.java
I wanted to be able to select a specific revision in a flexible way. Sometimes, this means using a more-or-less advanced revset.
> MercurialSCM: add support for revsets

- src/main/java/hudson/plugins/mercurial/MercurialChangeSet.java
- src/test/java/hudson/plugins/mercurial/MercurialRule.java
- src/test/java/hudson/plugins/mercurial/SCMTestBase.java
Newer versions of the email-ext-plugin no longer call getRevision and
getDate by reflection, and call these standard methods instead.
This pull request should fix https://issues.jenkins-ci.org/browse/JENKINS-30295. I hope it's useful to you!
> [JENKINS-30295] Implement getCommitId and getTimestamp methods of ChangeLogSet.Entry

- src/main/java/hudson/plugins/mercurial/Cache.java
- src/main/java/hudson/plugins/mercurial/MercurialInstallation.java
- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/main/resources/hudson/plugins/mercurial/MercurialInstallation/config.jelly
- src/main/resources/hudson/plugins/mercurial/MercurialInstallation/help-masterCacheRoot.html
- src/test/java/hudson/plugins/mercurial/CacheTest.java
- src/test/java/hudson/plugins/mercurial/CachingCustomDirSCMTest.java
[JENKINS-23571](https://issues.jenkins-ci.org/browse/JENKINS-23571)
This PR adds a new optional configuration option for "mercurial installations".
This new options allows users to customize the location of cached mercurial repositories on the jenkins master node when using repository caching. The default value remains unchanged ($JENKINS_HOME/hgcache)
This feature is useful for people who want to place this cache outside of $JENKINS_HOME.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jenkinsci/mercurial-plugin/91)
> [JENKINS-23571] Add configuration option for cache directory location

- src/test/java/hudson/plugins/mercurial/SCMTestBase.java
With the new changes to the plugin compatibility tester, a few of this plugin's tests fail, all implementing `SCMTestBase`. Currently, it isn't using `ParametersDefinitionProperty` to define parameters in one of the pipeline jobs. SECURITY-170 required some behavior changes upon the Jenkins 2.x release & the plugin compat tester can run against more recent versions, the tests are failing even though there are really no issues. I have run all the mercurial tests using `mvn test` as well as through the plugin compat tester, and there are now no errors.
I saw there were some comments about using `ParametersDefinitionProperty` at the point of change.  However, we basically have to do it at this point to run tests against the post `SECURITY-170` versions of Jenkins.
@reviewbybees
> PCT fixes: Use ParametersDefinitionProperty

- pom.xml
- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
[JENKINS-26100](https://issues.jenkins-ci.org/browse/JENKINS-26100)
FYI, I had some weird test failures locally when I ran `mvn clean install` but couldn't reproduce when running, say, `mvn clean install -Dtest=PipelineTest` so I'm not sure if they're environmental or what, so...hey, why not, here's a PR.
cc @reviewbybees
> [JENKINS-26100] Change buildEnvVars to take Run

- pom.xml
- src/main/java/hudson/plugins/mercurial/MercurialSCMBuilder.java
- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/main/java/hudson/plugins/mercurial/MercurialSCMSourceContext.java
- src/main/java/hudson/plugins/mercurial/MercurialSCMSourceRequest.java
- src/main/java/hudson/plugins/mercurial/MercurialStatus.java
- src/main/java/hudson/plugins/mercurial/traits/CleanMercurialSCMSourceTrait.java
- src/main/java/hudson/plugins/mercurial/traits/MercurialBrowserSCMSourceTrait.java
- src/main/java/hudson/plugins/mercurial/traits/MercurialInstallationSCMSourceTrait.java
- src/main/resources/hudson/plugins/mercurial/MercurialSCMSource/config-detail.jelly
- src/main/resources/hudson/plugins/mercurial/MercurialSCMSource/config-detail_en.properties
- src/main/resources/hudson/plugins/mercurial/MercurialSCMSource/config-detail_en_US.properties
- src/main/resources/hudson/plugins/mercurial/MercurialSCMSource/help-branchPattern.html
- src/main/resources/hudson/plugins/mercurial/MercurialSCMSource/help-clean.html
- src/main/resources/hudson/plugins/mercurial/MercurialSCMSource/help-modules.html
- src/main/resources/hudson/plugins/mercurial/MercurialSCMSource/help-subdir.html
- src/main/resources/hudson/plugins/mercurial/traits/CleanMercurialSCMSourceTrait/help.html
- src/main/resources/hudson/plugins/mercurial/traits/MercurialBrowserSCMSourceTrait/config.jelly
- src/main/resources/hudson/plugins/mercurial/traits/MercurialInstallationSCMSourceTrait/config.jelly
- src/main/resources/hudson/plugins/mercurial/traits/Messages.properties
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/36
See [JENKINS-43507](https://issues.jenkins-ci.org/browse/JENKINS-43507)
@reviewbybees
Todo
> [JENKINS-43507] Allow SCMSource and SCMNavigator subtypes to share common traits

- src/main/resources/hudson/plugins/mercurial/browser/HgWeb/help-url.html
The main Mercurial repository was migrated from http://selenic.com/repo/hg to https://www.mercurial-scm.org/repo/hg/
> Update example hg web link

- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
This fixes the missing credentialsId when polling for changes in a multibranch pipeline (see https://issues.jenkins-ci.org/browse/JENKINS-45806 for details).
> [JENKINS-45806] Mercurial doesn't use credentials in multibranch pipeline

- src/main/resources/hudson/plugins/mercurial/browser/RhodeCode/help-url.html
The main Mercurial repository was migrated from http://selenic.com/repo/hg to https://www.mercurial-scm.org/repo/hg/
> Update example rhodecode link

- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
getRepoLocation() returns a path with a `/` separator, but on Windows hgrc contains `\` paths for local clones.
So I propose we simply search for the `default` path in the file and replace it without checking its value. After a clone it has been set by Mercurial and must match what we gave it, short of the directory separator.
I hesitated just replacing `\` by `/` in hgrcText, seeing how more complex the code looks now.
> FIX repository cache w/o sharing fails on Windows

- pom.xml
- src/test/resources/hudson/plugins/mercurial/MercurialContainer/Dockerfile
The old version could not be used anymore. Building the ssh container failed due to issues with the used ubuntu base image.
For the respective change in docker-fixtures see: https://github.com/jenkinsci/docker-fixtures/pull/21
> Fix docker fixtures

- pom.xml
Raise minimum Jenkins version to 1st LTS release with Java 8 support.
The "credentials" plugin required a small update, otherwise InjectedTest would fail with:
> Folders Plugin v6.1.0 failed to load.
> Credentials Plugin v2.1.10 is older than required. To fix, install v2.1.11 or later.
> Upgrade to Java 8 and latest parent pom

- src/main/java/hudson/plugins/mercurial/traits/CleanMercurialSCMSourceTrait.java
- src/main/java/hudson/plugins/mercurial/traits/MercurialBrowserSCMSourceTrait.java
- src/main/java/hudson/plugins/mercurial/traits/MercurialInstallationSCMSourceTrait.java
Always override `getBuilderClass`, `getContextClass`, `getSourceClass`, `getScmClass`.
This should make sure that the traits cannot be applied in unintended places.
> Restrict all traits stricter to Mercurial

- src/test/java/hudson/plugins/mercurial/browser/HgBrowserSelectionTest.java
Observed in PCT runs:
```
java.lang.AssertionError: wrong url expected: java.net.URL<http://bitbucket.org/> but was: java.net.URL<http://bitbucket.org/>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at hudson.plugins.mercurial.browser.HgBrowserSelectionTest.browsersAvailableInDropDown(HgBrowserSelectionTest.java:51)
```
presumably since this host maps to multiple IPs. CC @bmunozm
> Do not rely on URL.equals in a test

- pom.xml
- src/test/java/hudson/plugins/mercurial/HgExeFunctionalTest.java
May as a side effect fix a PCT failure reported by @bmunozm, probably caused by mismatch between `workflow-support` versions in primary and `tests` classifier:
```
java.io.IOException: Pipeline: Groovy version 2.71 failed to load.
- Pipeline: Supporting APIs version 2.17 is older than required. To fix, install version 3.3 or later.
```
> Switch to a BOM

- src/main/resources/hudson/plugins/mercurial/MercurialInstallation/config.jelly
- src/main/resources/hudson/plugins/mercurial/MercurialSCM/config.jelly
[https://issues.jenkins-ci.org/browse/JENKINS-55787](https://issues.jenkins-ci.org/browse/JENKINS-55787)
Basically checkboxes should have labels, splitting the labels away from their checkboxes is poor UX, poor accessibility. This change brings the layout more inline with how normal settings UIs lay out checkboxes.
This supersedes #122
> [JENKINS-55787] Switch labels from entry to checkbox

- pom.xml
Trying to fix https://github.com/jenkinsci/mercurial-plugin/pull/135#issuecomment-608077275 by working around a regression from https://github.com/junit-team/junit4/pull/1517.
> reuseForks=false

- src/test/java/hudson/plugins/mercurial/MercurialContainer.java
Uses https://github.com/jenkinsci/jenkins-test-harness/pull/77 and allows us to pick up https://github.com/jenkinsci/jenkins-test-harness/pull/206 which is helpful for example in understanding when you need to
```bash
export SHARED_DOCKER_SERVICE=true
```
> Use JenkinsRule.waitOnline

- LICENSE
This adds an explicit license file at the root of the project. The license added is the same one specified in the pom.xml. Note that I've only added Jesse Glick's copyright notice, but there's plenty of others who should probably also get added.
> Add explicit license file to root of project

- src/main/java/hudson/plugins/mercurial/browser/ScmManager.java
- src/main/resources/hudson/plugins/mercurial/browser/ScmManager/config.jelly
- src/main/resources/hudson/plugins/mercurial/browser/ScmManager/help-url.html
- src/test/java/hudson/plugins/mercurial/browser/ScmManagerTest.java
This adds support for the [SCM-Manager](https://scm-manager.org) web frontend (like the already existing hgweb, bitbucket, etc). Generates URLs for viewing changesets, files and diffs.
It can be tested with the following public SCM-Manager repository [jenkins-plugin/hello-hg-shell](https://next-scm.cloudogu.com/scm/repo/jenkins-plugin/hello-hg-shell).
> Add SCM-Manager repository browser

- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/test/java/hudson/plugins/mercurial/MercurialSCMSource2Test.java
> [JENKINS-48867] A failure during branch indexing should be propagated so branches are not lost

- src/test/java/hudson/plugins/mercurial/FunctionalTest.java
This test started failing against 2.266 due apparently to https://github.com/jenkinsci/jenkins/pull/5028. (Not exactly sure how it _passed_ before that.)
> Fixing FunctionalTest.branches on newer Jenkins versions

- pom.xml
- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/test/java/hudson/plugins/mercurial/MatrixProjectTest.java
- src/test/java/hudson/plugins/mercurial/SCMTestBase.java
This plugin is deprecated—long superseded by Pipeline. The immediate impetus is test failures (locally, not in CI, and evidently flaky)
```
expected:<[[r1f2], [r2f2]]> but was:<[[r2f2], [r1f2]]>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:120)
at hudson.plugins.mercurial.SCMTestBase.assertChangeSetPaths(SCMTestBase.java:692)
at hudson.plugins.mercurial.SCMTestBase.changelogInMultiSCM(SCMTestBase.java:554)
```
> Removing integration with multiple-scms plugin

- src/test/java/hudson/plugins/mercurial/MercurialRule.java
- src/test/java/hudson/plugins/mercurial/PipelineTest.java
Amends #167, which broke some CI environments such as https://github.com/jenkinsci/plugin-compat-tester/blob/bb4f15c859c18865854168542a28d903c41dcab9/Dockerfile
> Skip PipelineTest.modernHook if Hg is using Python 2

- .github/dependabot.yml
- pom.xml
[JENKINS-65175](https://issues.jenkins.io/browse/JENKINS-65175): reverts #157.
The cleaner fix would likely be that suggested in a duplicate [JENKINS-66997](https://issues.jenkins.io/browse/JENKINS-66997):
```diff
diff --git a/src/main/java/hudson/plugins/mercurial/MercurialSCM.java b/src/main/java/hudson/plugins/mercurial/MercurialSCM.java
index e11cd3b..9d8b37f 100755
--- a/src/main/java/hudson/plugins/mercurial/MercurialSCM.java
+++ b/src/main/java/hudson/plugins/mercurial/MercurialSCM.java
@@ -813,6 +813,7 @@ public class MercurialSCM extends SCM implements Serializable {
if (hgrc.exists()) {
try (InputStream is = hgrc.read()) {
Ini hgrcIni = new Ini(is);
+                        hgrcIni.getConfig().setEscape(false);
hgrcIni.put("paths", "default", getSource(env));
try (OutputStream …
```
> [JENKINS-65175] Revert `ini4j` upgrade

- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/test/java/hudson/plugins/mercurial/MercurialSCMTest.java
Backports #212 to 2.15.x. CC @Pldi23
> [JENKINS-68562] Fix Mercurial checkouts on the built-in node for Windows controllers

- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/main/java/hudson/plugins/mercurial/browser/HgBrowser.java
Prevented CD release: https://github.com/jenkinsci/mercurial-plugin/runs/8015731971?check_suite_focus=true#step:4:157
> Javadoc errors & warnings

- .gitpod.Dockerfile
- .gitpod.yml
Removes the multiple JDKs installations in Gitpod as Java17 is not a requirement anymore for VSC plugins.
> Optimize gitpod config
