- pom.xml
- src/main/java/hudson/plugins/mercurial/Cache.java
- src/main/java/hudson/plugins/mercurial/ChangeComparator.java
- src/main/java/hudson/plugins/mercurial/HgExe.java
- src/main/java/hudson/plugins/mercurial/MercurialInstallation.java
- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/main/java/hudson/plugins/mercurial/MercurialStatus.java
It also allows to setup FindBugs enforcing on https://jenkins.ci.cloudbees.com/job/plugins/job/mercurial-plugin/
> Enable FindBugs on the verify stage

- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
[JENKINS-29311](https://issues.jenkins-ci.org/browse/JENKINS-29311)
@reviewbybees
> [JENKINS-29311] Avoid deprecated call

- src/main/resources/hudson/plugins/mercurial/MercurialChangeSetList/digest.jelly
- src/main/resources/hudson/plugins/mercurial/MercurialInstallation/config.jelly
- src/main/resources/hudson/plugins/mercurial/MercurialRevisionColumn/column.jelly
- src/main/resources/hudson/plugins/mercurial/MercurialRevisionColumn/columnHeader.jelly
- src/main/resources/hudson/plugins/mercurial/MercurialRevisionColumn/index.jelly
- src/main/resources/hudson/plugins/mercurial/MercurialSCM/config.jelly
- src/main/resources/hudson/plugins/mercurial/MercurialTagAction/index.jelly
- src/main/resources/hudson/plugins/mercurial/MercurialTagAction/summary.jelly
- src/main/resources/hudson/plugins/mercurial/browser/BitBucket/config.jelly
- src/main/resources/hudson/plugins/mercurial/browser/FishEye/config.jelly
- src/main/resources/hudson/plugins/mercurial/browser/GoogleCode/config.jelly
- src/main/resources/hudson/plugins/mercurial/browser/HgWeb/config.jelly
- src/main/resources/hudson/plugins/mercurial/browser/KilnHG/config.jelly
- src/main/resources/hudson/plugins/mercurial/browser/RhodeCode/config.jelly
- src/main/resources/index.jelly
> Add escape-by-default to jelly files.

- src/test/java/hudson/plugins/mercurial/ChangeComparatorTest.java
Looking for a node from a Computer that's null.  Changed to id the node from Jenkins itself.
@reviewbybees
> Fix NullPointerException in test

- pom.xml
- src/main/java/hudson/plugins/mercurial/HgExe.java
Follow up on #78
Did not have time to include the change so that build passes against 2.x baseline, so included it in this follow up PR.
@reviewbybees esp. @jglick
> Fix PCT against 2.x line

- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
Analogous to https://github.com/jenkinsci/git-plugin/pull/403.
@reviewbybees
> Check EXTENDED_READ, not CONFIGURE, on a context

- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/test/java/hudson/plugins/mercurial/PipelineTest.java
[JENKINS-36219](https://issues.jenkins-ci.org/browse/JENKINS-36219)
Clones tests from https://github.com/jenkinsci/workflow-multibranch-plugin/pull/18.
@reviewbybees
> [JENKINS-36219] Changelogs not displayed for Mercurial branch projects

- pom.xml
Allow `MercurialSampleRepoRule` from #81 to be used from other plugins’ tests.
@reviewbybees
> Create a test JAR

- pom.xml
- src/test/java/hudson/plugins/mercurial/PipelineTest.java
> Obsolete approveSignature calls

- pom.xml
- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/test/java/hudson/plugins/mercurial/SCMTestBase.java
[JENKINS-37274](https://issues.jenkins-ci.org/browse/JENKINS-37274)
@reviewbybees
> [JENKINS-37274] Suppress a confusing bit of output

- pom.xml
- src/main/java/hudson/plugins/mercurial/MercurialCommitPayload.java
- src/main/java/hudson/plugins/mercurial/MercurialSCMHeadEvent.java
- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/main/java/hudson/plugins/mercurial/MercurialStatus.java
- src/main/java/hudson/plugins/mercurial/MercurialStatusCrumbExclusion.java
- src/test/java/hudson/plugins/mercurial/CustomConfigTest.java
- src/test/java/hudson/plugins/mercurial/MercurialSampleRepoRule.java
- src/test/java/hudson/plugins/mercurial/PipelineTest.java
See [JENKINS-39355](https://issues.jenkins-ci.org/browse/JENKINS-39355)
@reviewbybees esp @jglick 
(implementing an `SCMFileSystem` is left as an exercise to the reader!)
> [JENKINS-39355 follow up] Adapt to SCM API 2.0 APIs

- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
See [JENKINS-40836](https://issues.jenkins-ci.org/browse/JENKINS-40836)
Depends on https://github.com/jenkinsci/mercurial-plugin/pull/92 and https://github.com/jenkinsci/scm-api-plugin/pull/20
@reviewbybees
> [JENKINS-40836] Report primary branch

- pom.xml
- src/main/java/hudson/plugins/mercurial/MercurialSCMHeadEvent.java
- src/main/java/hudson/plugins/mercurial/MercurialStatus.java
See [JENKINS-41814](https://issues.jenkins-ci.org/browse/JENKINS-41814)
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/27
@reviewbybees
> [FIXED JENKINS-41814] Expose event origin to listeners

- pom.xml
- src/test/java/hudson/plugins/mercurial/MercurialSampleRepoRule.java
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/32.
@reviewbybees
> Using official version of AbstractSampleDVCSRepoRule

- src/main/java/hudson/plugins/mercurial/MercurialStatus.java
- src/test/java/hudson/plugins/mercurial/MercurialStatusTest.java
https://issues.jenkins-ci.org/browse/JENKINS-26762
> [JENKINS-26762] notifyCommit: ignore trailing forward slashes when comparing URLs

- src/main/resources/hudson/plugins/mercurial/MercurialSCM/buildEnv.groovy
- src/main/resources/hudson/plugins/mercurial/MercurialSCM/buildEnv.properties
Analogous to https://github.com/jenkinsci/git-plugin/pull/508.
@reviewbybees
> [JENKINS-26100] Supply MercurialSCM/buildEnv

- pom.xml
- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
> [JENKINS-43507] Pick up new releases

- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/test/java/hudson/plugins/mercurial/PipelineTest.java
- src/test/java/hudson/plugins/mercurial/SCMTestBase.java
[JENKINS-42278](https://issues.jenkins-ci.org/browse/JENKINS-42278)
Supersedes #106: a bit simpler fix, with a test.
@reviewbybees
> [JENKINS-42278] Fix probe for Jenkinsfile

- src/main/java/hudson/plugins/mercurial/HgExe.java
- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/test/java/hudson/plugins/mercurial/MercurialSCMSource2Test.java
Subsumes #108 and adds a test. Corrects regression by @stephenc in #103.
@reviewbybees
> [JENKINS-45806] withCredentialsId needed

- pom.xml
- src/main/java/hudson/plugins/mercurial/HgExe.java
- src/test/java/hudson/plugins/mercurial/MercurialContainer.java
- src/test/resources/hudson/plugins/mercurial/MercurialContainer/Dockerfile
> Updated Docker fixture

- pom.xml
- src/main/java/hudson/plugins/mercurial/ChangeComparator.java
- src/main/java/hudson/plugins/mercurial/MercurialInstallation.java
- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/main/java/hudson/plugins/mercurial/MercurialStatus.java
- src/test/resources/hudson/plugins/mercurial/MercurialContainer/Dockerfile
Integrates https://github.com/jenkinsci/docker-fixtures/pull/11.
@reviewbybees
> docker-fixtures update

- pom.xml
- src/test/java/hudson/plugins/mercurial/FunctionalTest.java
- src/test/java/hudson/plugins/mercurial/MercurialContainerTest.java
- src/test/java/hudson/plugins/mercurial/MercurialSCMSource2Test.java
- src/test/java/hudson/plugins/mercurial/PipelineTest.java
Subsumes #115 and downstream of https://github.com/jenkinsci/docker-fixtures/pull/12.
@reviewbybees
> Use DockerClassRule

- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/test/java/hudson/plugins/mercurial/MercurialSCMSource2Test.java
[JENKINS-51530](https://issues.jenkins-ci.org/browse/JENKINS-51530)
> [JENKINS-51530] added a workaround for JENKINS-26535

- src/main/java/hudson/plugins/mercurial/MercurialChangeLogParser.java
- src/main/java/hudson/plugins/mercurial/MercurialChangeSet.java
- src/test/java/hudson/plugins/mercurial/ChangelogTest.java
- src/test/java/hudson/plugins/mercurial/FunctionalTest.java
- src/test/java/hudson/plugins/mercurial/MercurialChangeLogParserTest.java
- src/test/java/hudson/plugins/mercurial/MercurialContainer.java
- src/test/java/hudson/plugins/mercurial/MercurialRule.java
- src/test/java/hudson/plugins/mercurial/SCMTestBase.java
- src/test/resources/hudson/plugins/mercurial/MercurialContainer/Dockerfile
> [JENKINS-55319] Handle spaces in filenames

- src/main/java/hudson/plugins/mercurial/Cache.java
- src/main/java/hudson/plugins/mercurial/HgExe.java
- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/test/java/hudson/plugins/mercurial/HgExeFunctionalTest.java
- src/test/java/hudson/plugins/mercurial/MercurialChangeLogParserTest.java
It's more easy to review this with whitespace changes ignored (because indentation changed).
> Implement AutoCloseable for HgExe and use try-with-resources

- pom.xml
- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/test/java/hudson/plugins/mercurial/MercurialSCMSourceTest.java
Downstream of https://github.com/jenkinsci/scm-api-plugin/pull/65. Probably complementary to #119.
> [JENKINS-43802] Implementing retrieve/retrieveRevisions with an Item context

- README.md
As suggested by @jglick in #141
> Specify languages for README snippets

- pom.xml
- src/test/java/hudson/plugins/mercurial/MercurialSCMSource2Test.java
Downstream of https://github.com/jenkinsci/jenkins-test-harness/pull/242.
> Using FlagRule

- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/test/java/hudson/plugins/mercurial/MercurialSCMSource2Test.java
#119 but with test coverage. Subsumes #149.
> [JENKINS-46851] Need to pass credentials when looking up a commit

- README.md
- src/main/java/hudson/plugins/mercurial/MercurialStatus.java
- src/test/java/hudson/plugins/mercurial/MercurialRule.java
https://docs.python.org/2/library/2to3.html and https://stackoverflow.com/a/30760915/12916
> Make PipelineTest.modernHook pass with Python 3

- README.md
- src/test/java/hudson/plugins/mercurial/MercurialRule.java
- src/test/resources/hook.py
> Expose hook script into documentation

- src/test/java/hudson/plugins/mercurial/MercurialRule.java
Test changes in #173 did not work.
> Fixing `MercurialRule.registerHook`

- .github/workflows/jenkins-security-scan.yml
https://github.com/jenkins-infra/jenkins-security-scan/pull/5
> Pick up `jenkins-security-scan` v2

- pom.xml
- src/main/java/hudson/plugins/mercurial/MercurialSCM.java
- src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
- src/main/java/hudson/plugins/mercurial/MercurialStatus.java
- src/main/java/hudson/plugins/mercurial/MercurialStatusCrumbExclusion.java
- src/test/java/hudson/plugins/mercurial/HgExeTest.java
- src/test/java/hudson/plugins/mercurial/MercurialContainer.java
- src/test/java/hudson/plugins/mercurial/MercurialRule.java
Remove usages of Commons Lang 2
mvn clean install
> Remove usages of Commons Lang 2
